project:
  type: website

website:
  title: "Data Science and Statistics in R for Fellowship"
  repo-url: https://caius-gibeily.github.io/r4dss25/
  repo-actions: [edit, issue]
  repo-subdir: "docs"
  page-navigation: true
  sidebar:
    contents:

      - href: index.qmd
      - section: R for Data Science 2025
        contents:
          - intro.qmd
          
theme:
  light: cosmo
  dark: darkly
